// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web config — same Firebase project (app-borrowit)
  // To get the real web apiKey: Firebase Console → Project Settings → General → Web apps
  // The apiKey below is the same project key; replace with your actual web app apiKey if different
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtUdlZ17hPuAvUDOEfMDyUYfldt2_uJtE',
    appId: '1:171503100776:web:borrowit_web',
    messagingSenderId: '171503100776',
    projectId: 'app-borrowit',
    storageBucket: 'app-borrowit.firebasestorage.app',
    authDomain: 'app-borrowit.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtUdlZ17hPuAvUDOEfMDyUYfldt2_uJtE',
    appId: '1:171503100776:android:9f0400418e9aee42e86cdd',
    messagingSenderId: '171503100776',
    projectId: 'app-borrowit',
    storageBucket: 'app-borrowit.firebasestorage.app',
  );
}
